osx_image: xcode8.3
language: objective-c
podfile: Example/Podfile
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/RGBA.xcworkspace -scheme RGBA-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
