osx_image: xcode8.3
language: objective-c
podfile: Example/Podfile
script:
  - set -o pipefail && xcodebuild test -workspace Example/RGBA.xcworkspace -scheme RGBA-Example -sdk iphonesimulator -configuration Debug | xcpretty
  - pod lib lint
